### ISSUE TITLE
Make openapi meta configurable (version, title, description, servers,...)

### ISSUE THREAD

**Issue by spajic** [spajic/lobanov#46]
См `lobanov/configuration.rb`

Там есть уже один конфигурируемый аттрибут: namespaces_to_ignore

Нужно добавить ещё атрибутов для версии openapi, title, description, version, servers

Вот этот блок:

```
openapi: 3.0.1
info:
title: Test fruits API for Lobanov development
description: API which is used to develop Lobanov gem.
version: 0.0.1
```

И ещё секция servers:

```
servers:
url: http://localhost:3000/
    description: Development server
url: https://staging.3commas.io/
    description: Staging server
url: https://3commas.io/
    description: Production server
```
